# coding: utf-8

"""
    ChronoSheets API

    ChronoSheets is a flexible timesheet solution for small to medium businesses, it is free for small teams of up to 5 and there are iOS and Android apps available.  Use the ChronoSheets API to create your own custom integrations.  # noqa: E501

    OpenAPI spec version: v1
    Contact: lachlan@chronosheets.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class CSJobSeriesReportItem(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'start_date': 'datetime',
        'end_date': 'datetime',
        'job_id': 'int',
        'client_id': 'int',
        'client_name': 'str',
        'project_id': 'int',
        'project_name': 'str',
        'span_seconds': 'int',
        'job_code': 'str'
    }

    attribute_map = {
        'start_date': 'StartDate',
        'end_date': 'EndDate',
        'job_id': 'JobId',
        'client_id': 'ClientId',
        'client_name': 'ClientName',
        'project_id': 'ProjectId',
        'project_name': 'ProjectName',
        'span_seconds': 'SpanSeconds',
        'job_code': 'JobCode'
    }

    def __init__(self, start_date=None, end_date=None, job_id=None, client_id=None, client_name=None, project_id=None, project_name=None, span_seconds=None, job_code=None):  # noqa: E501
        """CSJobSeriesReportItem - a model defined in Swagger"""  # noqa: E501

        self._start_date = None
        self._end_date = None
        self._job_id = None
        self._client_id = None
        self._client_name = None
        self._project_id = None
        self._project_name = None
        self._span_seconds = None
        self._job_code = None
        self.discriminator = None

        if start_date is not None:
            self.start_date = start_date
        if end_date is not None:
            self.end_date = end_date
        if job_id is not None:
            self.job_id = job_id
        if client_id is not None:
            self.client_id = client_id
        if client_name is not None:
            self.client_name = client_name
        if project_id is not None:
            self.project_id = project_id
        if project_name is not None:
            self.project_name = project_name
        if span_seconds is not None:
            self.span_seconds = span_seconds
        if job_code is not None:
            self.job_code = job_code

    @property
    def start_date(self):
        """Gets the start_date of this CSJobSeriesReportItem.  # noqa: E501


        :return: The start_date of this CSJobSeriesReportItem.  # noqa: E501
        :rtype: datetime
        """
        return self._start_date

    @start_date.setter
    def start_date(self, start_date):
        """Sets the start_date of this CSJobSeriesReportItem.


        :param start_date: The start_date of this CSJobSeriesReportItem.  # noqa: E501
        :type: datetime
        """

        self._start_date = start_date

    @property
    def end_date(self):
        """Gets the end_date of this CSJobSeriesReportItem.  # noqa: E501


        :return: The end_date of this CSJobSeriesReportItem.  # noqa: E501
        :rtype: datetime
        """
        return self._end_date

    @end_date.setter
    def end_date(self, end_date):
        """Sets the end_date of this CSJobSeriesReportItem.


        :param end_date: The end_date of this CSJobSeriesReportItem.  # noqa: E501
        :type: datetime
        """

        self._end_date = end_date

    @property
    def job_id(self):
        """Gets the job_id of this CSJobSeriesReportItem.  # noqa: E501


        :return: The job_id of this CSJobSeriesReportItem.  # noqa: E501
        :rtype: int
        """
        return self._job_id

    @job_id.setter
    def job_id(self, job_id):
        """Sets the job_id of this CSJobSeriesReportItem.


        :param job_id: The job_id of this CSJobSeriesReportItem.  # noqa: E501
        :type: int
        """

        self._job_id = job_id

    @property
    def client_id(self):
        """Gets the client_id of this CSJobSeriesReportItem.  # noqa: E501


        :return: The client_id of this CSJobSeriesReportItem.  # noqa: E501
        :rtype: int
        """
        return self._client_id

    @client_id.setter
    def client_id(self, client_id):
        """Sets the client_id of this CSJobSeriesReportItem.


        :param client_id: The client_id of this CSJobSeriesReportItem.  # noqa: E501
        :type: int
        """

        self._client_id = client_id

    @property
    def client_name(self):
        """Gets the client_name of this CSJobSeriesReportItem.  # noqa: E501


        :return: The client_name of this CSJobSeriesReportItem.  # noqa: E501
        :rtype: str
        """
        return self._client_name

    @client_name.setter
    def client_name(self, client_name):
        """Sets the client_name of this CSJobSeriesReportItem.


        :param client_name: The client_name of this CSJobSeriesReportItem.  # noqa: E501
        :type: str
        """

        self._client_name = client_name

    @property
    def project_id(self):
        """Gets the project_id of this CSJobSeriesReportItem.  # noqa: E501


        :return: The project_id of this CSJobSeriesReportItem.  # noqa: E501
        :rtype: int
        """
        return self._project_id

    @project_id.setter
    def project_id(self, project_id):
        """Sets the project_id of this CSJobSeriesReportItem.


        :param project_id: The project_id of this CSJobSeriesReportItem.  # noqa: E501
        :type: int
        """

        self._project_id = project_id

    @property
    def project_name(self):
        """Gets the project_name of this CSJobSeriesReportItem.  # noqa: E501


        :return: The project_name of this CSJobSeriesReportItem.  # noqa: E501
        :rtype: str
        """
        return self._project_name

    @project_name.setter
    def project_name(self, project_name):
        """Sets the project_name of this CSJobSeriesReportItem.


        :param project_name: The project_name of this CSJobSeriesReportItem.  # noqa: E501
        :type: str
        """

        self._project_name = project_name

    @property
    def span_seconds(self):
        """Gets the span_seconds of this CSJobSeriesReportItem.  # noqa: E501


        :return: The span_seconds of this CSJobSeriesReportItem.  # noqa: E501
        :rtype: int
        """
        return self._span_seconds

    @span_seconds.setter
    def span_seconds(self, span_seconds):
        """Sets the span_seconds of this CSJobSeriesReportItem.


        :param span_seconds: The span_seconds of this CSJobSeriesReportItem.  # noqa: E501
        :type: int
        """

        self._span_seconds = span_seconds

    @property
    def job_code(self):
        """Gets the job_code of this CSJobSeriesReportItem.  # noqa: E501


        :return: The job_code of this CSJobSeriesReportItem.  # noqa: E501
        :rtype: str
        """
        return self._job_code

    @job_code.setter
    def job_code(self, job_code):
        """Sets the job_code of this CSJobSeriesReportItem.


        :param job_code: The job_code of this CSJobSeriesReportItem.  # noqa: E501
        :type: str
        """

        self._job_code = job_code

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CSJobSeriesReportItem):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
