# coding: utf-8

"""
    ChronoSheets API

    <div style='font-size: 14px!important;font-family: Open Sans,sans-serif!important;color: #3b4151!important;'><p>      ChronoSheets is a flexible timesheet solution for small to medium businesses, it is free for small teams of up to 3 and there are iOS and Android apps available.  Use the ChronoSheets API to create your own custom integrations.  Before starting, sign up for a ChronoSheets account at <a target='_BLANK' href='http://tsheets.xyz/signup'>http://tsheets.xyz/signup</a>.  </p></div><div id='cs-extra-info'></div>  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import re  # noqa: F401

# python 2 and python 3 compatibility library
import six

from ChronoSheetsAPI.api_client import ApiClient
from ChronoSheetsAPI.exceptions import (  # noqa: F401
    ApiTypeError,
    ApiValueError
)


class ReportsApi(object):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

    def reports_get_all_charts_data_admin(self, start_date, end_date, x_chronosheets_auth, **kwargs):  # noqa: E501
        """Get Consolidated Admin Reports Data (Jobs, Tasks, Clients and Projects).  These are the organisation wide reports, with data from potentially all employees.    Requires the 'ReportAdmin' permission.  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.reports_get_all_charts_data_admin(start_date, end_date, x_chronosheets_auth, async_req=True)
        >>> result = thread.get()

        :param async_req bool: execute request asynchronously
        :param datetime start_date: The start date for the date range.  Report data in the response is after this date (required)
        :param datetime end_date: The end date for the date range.  Report data in the response is before this date (required)
        :param str x_chronosheets_auth: The ChronoSheets Auth Token (required)
        :param str user_ids: A comma-separated list of user Ids, if you want to filter the report data to particular users.  If you want all, send a blank string.
        :param str force_only_this_chart: A flag to indicate which report data you require.  Choose a particular set of data, or if you want all data use the 'NotForced' option.
        :param _preload_content: if False, the urllib3.HTTPResponse object will
                                 be returned without reading/decoding response
                                 data. Default is True.
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :return: ApiResponseCombinedReportsData
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        return self.reports_get_all_charts_data_admin_with_http_info(start_date, end_date, x_chronosheets_auth, **kwargs)  # noqa: E501

    def reports_get_all_charts_data_admin_with_http_info(self, start_date, end_date, x_chronosheets_auth, **kwargs):  # noqa: E501
        """Get Consolidated Admin Reports Data (Jobs, Tasks, Clients and Projects).  These are the organisation wide reports, with data from potentially all employees.    Requires the 'ReportAdmin' permission.  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.reports_get_all_charts_data_admin_with_http_info(start_date, end_date, x_chronosheets_auth, async_req=True)
        >>> result = thread.get()

        :param async_req bool: execute request asynchronously
        :param datetime start_date: The start date for the date range.  Report data in the response is after this date (required)
        :param datetime end_date: The end date for the date range.  Report data in the response is before this date (required)
        :param str x_chronosheets_auth: The ChronoSheets Auth Token (required)
        :param str user_ids: A comma-separated list of user Ids, if you want to filter the report data to particular users.  If you want all, send a blank string.
        :param str force_only_this_chart: A flag to indicate which report data you require.  Choose a particular set of data, or if you want all data use the 'NotForced' option.
        :param _return_http_data_only: response data without head status code
                                       and headers
        :param _preload_content: if False, the urllib3.HTTPResponse object will
                                 be returned without reading/decoding response
                                 data. Default is True.
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :return: tuple(ApiResponseCombinedReportsData, status_code(int), headers(HTTPHeaderDict))
                 If the method is called asynchronously,
                 returns the request thread.
        """

        local_var_params = locals()

        all_params = [
            'start_date',
            'end_date',
            'x_chronosheets_auth',
            'user_ids',
            'force_only_this_chart'
        ]
        all_params.extend(
            [
                'async_req',
                '_return_http_data_only',
                '_preload_content',
                '_request_timeout'
            ]
        )

        for key, val in six.iteritems(local_var_params['kwargs']):
            if key not in all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method reports_get_all_charts_data_admin" % key
                )
            local_var_params[key] = val
        del local_var_params['kwargs']
        # verify the required parameter 'start_date' is set
        if self.api_client.client_side_validation and ('start_date' not in local_var_params or  # noqa: E501
                                                        local_var_params['start_date'] is None):  # noqa: E501
            raise ApiValueError("Missing the required parameter `start_date` when calling `reports_get_all_charts_data_admin`")  # noqa: E501
        # verify the required parameter 'end_date' is set
        if self.api_client.client_side_validation and ('end_date' not in local_var_params or  # noqa: E501
                                                        local_var_params['end_date'] is None):  # noqa: E501
            raise ApiValueError("Missing the required parameter `end_date` when calling `reports_get_all_charts_data_admin`")  # noqa: E501
        # verify the required parameter 'x_chronosheets_auth' is set
        if self.api_client.client_side_validation and ('x_chronosheets_auth' not in local_var_params or  # noqa: E501
                                                        local_var_params['x_chronosheets_auth'] is None):  # noqa: E501
            raise ApiValueError("Missing the required parameter `x_chronosheets_auth` when calling `reports_get_all_charts_data_admin`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []
        if 'start_date' in local_var_params and local_var_params['start_date'] is not None:  # noqa: E501
            query_params.append(('StartDate', local_var_params['start_date']))  # noqa: E501
        if 'end_date' in local_var_params and local_var_params['end_date'] is not None:  # noqa: E501
            query_params.append(('EndDate', local_var_params['end_date']))  # noqa: E501
        if 'user_ids' in local_var_params and local_var_params['user_ids'] is not None:  # noqa: E501
            query_params.append(('UserIds', local_var_params['user_ids']))  # noqa: E501
        if 'force_only_this_chart' in local_var_params and local_var_params['force_only_this_chart'] is not None:  # noqa: E501
            query_params.append(('ForceOnlyThisChart', local_var_params['force_only_this_chart']))  # noqa: E501

        header_params = {}
        if 'x_chronosheets_auth' in local_var_params:
            header_params['x-chronosheets-auth'] = local_var_params['x_chronosheets_auth']  # noqa: E501

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json', 'text/json', 'application/xml', 'text/xml', 'multipart/form-data'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/Reports/GetAllChartsDataAdmin', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='ApiResponseCombinedReportsData',  # noqa: E501
            auth_settings=auth_settings,
            async_req=local_var_params.get('async_req'),
            _return_http_data_only=local_var_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=local_var_params.get('_preload_content', True),
            _request_timeout=local_var_params.get('_request_timeout'),
            collection_formats=collection_formats)

    def reports_get_all_charts_data_user(self, start_date, end_date, x_chronosheets_auth, **kwargs):  # noqa: E501
        """Get Consolidated User Reports Data (Jobs, Tasks, Clients and Projects).  These are the user's own reports.    Requires the 'ViewOwnReports' permission.  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.reports_get_all_charts_data_user(start_date, end_date, x_chronosheets_auth, async_req=True)
        >>> result = thread.get()

        :param async_req bool: execute request asynchronously
        :param datetime start_date: The start date for the date range.  Report data in the response is after this date (required)
        :param datetime end_date: The end date for the date range.  Report data in the response is before this date (required)
        :param str x_chronosheets_auth: The ChronoSheets Auth Token (required)
        :param _preload_content: if False, the urllib3.HTTPResponse object will
                                 be returned without reading/decoding response
                                 data. Default is True.
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :return: ApiResponseCombinedReportsData
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        return self.reports_get_all_charts_data_user_with_http_info(start_date, end_date, x_chronosheets_auth, **kwargs)  # noqa: E501

    def reports_get_all_charts_data_user_with_http_info(self, start_date, end_date, x_chronosheets_auth, **kwargs):  # noqa: E501
        """Get Consolidated User Reports Data (Jobs, Tasks, Clients and Projects).  These are the user's own reports.    Requires the 'ViewOwnReports' permission.  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.reports_get_all_charts_data_user_with_http_info(start_date, end_date, x_chronosheets_auth, async_req=True)
        >>> result = thread.get()

        :param async_req bool: execute request asynchronously
        :param datetime start_date: The start date for the date range.  Report data in the response is after this date (required)
        :param datetime end_date: The end date for the date range.  Report data in the response is before this date (required)
        :param str x_chronosheets_auth: The ChronoSheets Auth Token (required)
        :param _return_http_data_only: response data without head status code
                                       and headers
        :param _preload_content: if False, the urllib3.HTTPResponse object will
                                 be returned without reading/decoding response
                                 data. Default is True.
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :return: tuple(ApiResponseCombinedReportsData, status_code(int), headers(HTTPHeaderDict))
                 If the method is called asynchronously,
                 returns the request thread.
        """

        local_var_params = locals()

        all_params = [
            'start_date',
            'end_date',
            'x_chronosheets_auth'
        ]
        all_params.extend(
            [
                'async_req',
                '_return_http_data_only',
                '_preload_content',
                '_request_timeout'
            ]
        )

        for key, val in six.iteritems(local_var_params['kwargs']):
            if key not in all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method reports_get_all_charts_data_user" % key
                )
            local_var_params[key] = val
        del local_var_params['kwargs']
        # verify the required parameter 'start_date' is set
        if self.api_client.client_side_validation and ('start_date' not in local_var_params or  # noqa: E501
                                                        local_var_params['start_date'] is None):  # noqa: E501
            raise ApiValueError("Missing the required parameter `start_date` when calling `reports_get_all_charts_data_user`")  # noqa: E501
        # verify the required parameter 'end_date' is set
        if self.api_client.client_side_validation and ('end_date' not in local_var_params or  # noqa: E501
                                                        local_var_params['end_date'] is None):  # noqa: E501
            raise ApiValueError("Missing the required parameter `end_date` when calling `reports_get_all_charts_data_user`")  # noqa: E501
        # verify the required parameter 'x_chronosheets_auth' is set
        if self.api_client.client_side_validation and ('x_chronosheets_auth' not in local_var_params or  # noqa: E501
                                                        local_var_params['x_chronosheets_auth'] is None):  # noqa: E501
            raise ApiValueError("Missing the required parameter `x_chronosheets_auth` when calling `reports_get_all_charts_data_user`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []
        if 'start_date' in local_var_params and local_var_params['start_date'] is not None:  # noqa: E501
            query_params.append(('StartDate', local_var_params['start_date']))  # noqa: E501
        if 'end_date' in local_var_params and local_var_params['end_date'] is not None:  # noqa: E501
            query_params.append(('EndDate', local_var_params['end_date']))  # noqa: E501

        header_params = {}
        if 'x_chronosheets_auth' in local_var_params:
            header_params['x-chronosheets-auth'] = local_var_params['x_chronosheets_auth']  # noqa: E501

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json', 'text/json', 'application/xml', 'text/xml', 'multipart/form-data'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/Reports/GetAllChartsDataUser', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='ApiResponseCombinedReportsData',  # noqa: E501
            auth_settings=auth_settings,
            async_req=local_var_params.get('async_req'),
            _return_http_data_only=local_var_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=local_var_params.get('_preload_content', True),
            _request_timeout=local_var_params.get('_request_timeout'),
            collection_formats=collection_formats)

    def reports_get_fleet_summary_admin(self, start_date, end_date, x_chronosheets_auth, **kwargs):  # noqa: E501
        """Gets a summary report, which includes total distance travelled and total running costs, for vehicles within your organisation  Requires the 'ReportAdmin' permission.  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.reports_get_fleet_summary_admin(start_date, end_date, x_chronosheets_auth, async_req=True)
        >>> result = thread.get()

        :param async_req bool: execute request asynchronously
        :param datetime start_date: The start date for the date range.  Report data in the response is after this date (required)
        :param datetime end_date: The end date for the date range.  Report data in the response is before this date (required)
        :param str x_chronosheets_auth: The ChronoSheets Auth Token (required)
        :param str user_ids: A comma-separated list of user Ids, if you want to filter the report data to particular users.  If you want all, send a blank string.
        :param _preload_content: if False, the urllib3.HTTPResponse object will
                                 be returned without reading/decoding response
                                 data. Default is True.
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :return: ApiResponseListFleetSummaryReportItem
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        return self.reports_get_fleet_summary_admin_with_http_info(start_date, end_date, x_chronosheets_auth, **kwargs)  # noqa: E501

    def reports_get_fleet_summary_admin_with_http_info(self, start_date, end_date, x_chronosheets_auth, **kwargs):  # noqa: E501
        """Gets a summary report, which includes total distance travelled and total running costs, for vehicles within your organisation  Requires the 'ReportAdmin' permission.  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.reports_get_fleet_summary_admin_with_http_info(start_date, end_date, x_chronosheets_auth, async_req=True)
        >>> result = thread.get()

        :param async_req bool: execute request asynchronously
        :param datetime start_date: The start date for the date range.  Report data in the response is after this date (required)
        :param datetime end_date: The end date for the date range.  Report data in the response is before this date (required)
        :param str x_chronosheets_auth: The ChronoSheets Auth Token (required)
        :param str user_ids: A comma-separated list of user Ids, if you want to filter the report data to particular users.  If you want all, send a blank string.
        :param _return_http_data_only: response data without head status code
                                       and headers
        :param _preload_content: if False, the urllib3.HTTPResponse object will
                                 be returned without reading/decoding response
                                 data. Default is True.
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :return: tuple(ApiResponseListFleetSummaryReportItem, status_code(int), headers(HTTPHeaderDict))
                 If the method is called asynchronously,
                 returns the request thread.
        """

        local_var_params = locals()

        all_params = [
            'start_date',
            'end_date',
            'x_chronosheets_auth',
            'user_ids'
        ]
        all_params.extend(
            [
                'async_req',
                '_return_http_data_only',
                '_preload_content',
                '_request_timeout'
            ]
        )

        for key, val in six.iteritems(local_var_params['kwargs']):
            if key not in all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method reports_get_fleet_summary_admin" % key
                )
            local_var_params[key] = val
        del local_var_params['kwargs']
        # verify the required parameter 'start_date' is set
        if self.api_client.client_side_validation and ('start_date' not in local_var_params or  # noqa: E501
                                                        local_var_params['start_date'] is None):  # noqa: E501
            raise ApiValueError("Missing the required parameter `start_date` when calling `reports_get_fleet_summary_admin`")  # noqa: E501
        # verify the required parameter 'end_date' is set
        if self.api_client.client_side_validation and ('end_date' not in local_var_params or  # noqa: E501
                                                        local_var_params['end_date'] is None):  # noqa: E501
            raise ApiValueError("Missing the required parameter `end_date` when calling `reports_get_fleet_summary_admin`")  # noqa: E501
        # verify the required parameter 'x_chronosheets_auth' is set
        if self.api_client.client_side_validation and ('x_chronosheets_auth' not in local_var_params or  # noqa: E501
                                                        local_var_params['x_chronosheets_auth'] is None):  # noqa: E501
            raise ApiValueError("Missing the required parameter `x_chronosheets_auth` when calling `reports_get_fleet_summary_admin`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []
        if 'start_date' in local_var_params and local_var_params['start_date'] is not None:  # noqa: E501
            query_params.append(('StartDate', local_var_params['start_date']))  # noqa: E501
        if 'end_date' in local_var_params and local_var_params['end_date'] is not None:  # noqa: E501
            query_params.append(('EndDate', local_var_params['end_date']))  # noqa: E501
        if 'user_ids' in local_var_params and local_var_params['user_ids'] is not None:  # noqa: E501
            query_params.append(('UserIds', local_var_params['user_ids']))  # noqa: E501

        header_params = {}
        if 'x_chronosheets_auth' in local_var_params:
            header_params['x-chronosheets-auth'] = local_var_params['x_chronosheets_auth']  # noqa: E501

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json', 'text/json', 'application/xml', 'text/xml', 'multipart/form-data'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/Reports/GetFleetSummaryAdmin', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='ApiResponseListFleetSummaryReportItem',  # noqa: E501
            auth_settings=auth_settings,
            async_req=local_var_params.get('async_req'),
            _return_http_data_only=local_var_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=local_var_params.get('_preload_content', True),
            _request_timeout=local_var_params.get('_request_timeout'),
            collection_formats=collection_formats)

    def reports_get_org_trip_by_id(self, trip_id, x_chronosheets_auth, **kwargs):  # noqa: E501
        """Get trip by Id, for reporting purposes.    Requires the 'ReportAdmin' permission.  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.reports_get_org_trip_by_id(trip_id, x_chronosheets_auth, async_req=True)
        >>> result = thread.get()

        :param async_req bool: execute request asynchronously
        :param int trip_id: The ID of the Trip you want to get (required)
        :param str x_chronosheets_auth: The ChronoSheets Auth Token (required)
        :param _preload_content: if False, the urllib3.HTTPResponse object will
                                 be returned without reading/decoding response
                                 data. Default is True.
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :return: ApiResponseTrip
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        return self.reports_get_org_trip_by_id_with_http_info(trip_id, x_chronosheets_auth, **kwargs)  # noqa: E501

    def reports_get_org_trip_by_id_with_http_info(self, trip_id, x_chronosheets_auth, **kwargs):  # noqa: E501
        """Get trip by Id, for reporting purposes.    Requires the 'ReportAdmin' permission.  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.reports_get_org_trip_by_id_with_http_info(trip_id, x_chronosheets_auth, async_req=True)
        >>> result = thread.get()

        :param async_req bool: execute request asynchronously
        :param int trip_id: The ID of the Trip you want to get (required)
        :param str x_chronosheets_auth: The ChronoSheets Auth Token (required)
        :param _return_http_data_only: response data without head status code
                                       and headers
        :param _preload_content: if False, the urllib3.HTTPResponse object will
                                 be returned without reading/decoding response
                                 data. Default is True.
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :return: tuple(ApiResponseTrip, status_code(int), headers(HTTPHeaderDict))
                 If the method is called asynchronously,
                 returns the request thread.
        """

        local_var_params = locals()

        all_params = [
            'trip_id',
            'x_chronosheets_auth'
        ]
        all_params.extend(
            [
                'async_req',
                '_return_http_data_only',
                '_preload_content',
                '_request_timeout'
            ]
        )

        for key, val in six.iteritems(local_var_params['kwargs']):
            if key not in all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method reports_get_org_trip_by_id" % key
                )
            local_var_params[key] = val
        del local_var_params['kwargs']
        # verify the required parameter 'trip_id' is set
        if self.api_client.client_side_validation and ('trip_id' not in local_var_params or  # noqa: E501
                                                        local_var_params['trip_id'] is None):  # noqa: E501
            raise ApiValueError("Missing the required parameter `trip_id` when calling `reports_get_org_trip_by_id`")  # noqa: E501
        # verify the required parameter 'x_chronosheets_auth' is set
        if self.api_client.client_side_validation and ('x_chronosheets_auth' not in local_var_params or  # noqa: E501
                                                        local_var_params['x_chronosheets_auth'] is None):  # noqa: E501
            raise ApiValueError("Missing the required parameter `x_chronosheets_auth` when calling `reports_get_org_trip_by_id`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []
        if 'trip_id' in local_var_params and local_var_params['trip_id'] is not None:  # noqa: E501
            query_params.append(('TripId', local_var_params['trip_id']))  # noqa: E501

        header_params = {}
        if 'x_chronosheets_auth' in local_var_params:
            header_params['x-chronosheets-auth'] = local_var_params['x_chronosheets_auth']  # noqa: E501

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json', 'text/json', 'application/xml', 'text/xml', 'multipart/form-data'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/Reports/GetOrgTripById', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='ApiResponseTrip',  # noqa: E501
            auth_settings=auth_settings,
            async_req=local_var_params.get('async_req'),
            _return_http_data_only=local_var_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=local_var_params.get('_preload_content', True),
            _request_timeout=local_var_params.get('_request_timeout'),
            collection_formats=collection_formats)

    def reports_get_organisation_timesheet_file_attachments(self, start_date, end_date, x_chronosheets_auth, **kwargs):  # noqa: E501
        """Reports on Organisation timesheet file attachments (files uploaded and attached to timesheet records)  Requires the 'ReportAdmin' permission.  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.reports_get_organisation_timesheet_file_attachments(start_date, end_date, x_chronosheets_auth, async_req=True)
        >>> result = thread.get()

        :param async_req bool: execute request asynchronously
        :param datetime start_date: The start date for the date range.  Report data in the response is after this date (required)
        :param datetime end_date: The end date for the date range.  Report data in the response is before this date (required)
        :param str x_chronosheets_auth: The ChronoSheets Auth Token (required)
        :param int skip: Skip this many items
        :param int take: Take this many items
        :param str user_ids: A comma-separated list of user Ids, if you want to filter the report data to particular users.  If you want all, send a blank string.
        :param _preload_content: if False, the urllib3.HTTPResponse object will
                                 be returned without reading/decoding response
                                 data. Default is True.
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :return: ApiResponseForPaginatedListOrgReportTimesheetFileAttachment
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        return self.reports_get_organisation_timesheet_file_attachments_with_http_info(start_date, end_date, x_chronosheets_auth, **kwargs)  # noqa: E501

    def reports_get_organisation_timesheet_file_attachments_with_http_info(self, start_date, end_date, x_chronosheets_auth, **kwargs):  # noqa: E501
        """Reports on Organisation timesheet file attachments (files uploaded and attached to timesheet records)  Requires the 'ReportAdmin' permission.  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.reports_get_organisation_timesheet_file_attachments_with_http_info(start_date, end_date, x_chronosheets_auth, async_req=True)
        >>> result = thread.get()

        :param async_req bool: execute request asynchronously
        :param datetime start_date: The start date for the date range.  Report data in the response is after this date (required)
        :param datetime end_date: The end date for the date range.  Report data in the response is before this date (required)
        :param str x_chronosheets_auth: The ChronoSheets Auth Token (required)
        :param int skip: Skip this many items
        :param int take: Take this many items
        :param str user_ids: A comma-separated list of user Ids, if you want to filter the report data to particular users.  If you want all, send a blank string.
        :param _return_http_data_only: response data without head status code
                                       and headers
        :param _preload_content: if False, the urllib3.HTTPResponse object will
                                 be returned without reading/decoding response
                                 data. Default is True.
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :return: tuple(ApiResponseForPaginatedListOrgReportTimesheetFileAttachment, status_code(int), headers(HTTPHeaderDict))
                 If the method is called asynchronously,
                 returns the request thread.
        """

        local_var_params = locals()

        all_params = [
            'start_date',
            'end_date',
            'x_chronosheets_auth',
            'skip',
            'take',
            'user_ids'
        ]
        all_params.extend(
            [
                'async_req',
                '_return_http_data_only',
                '_preload_content',
                '_request_timeout'
            ]
        )

        for key, val in six.iteritems(local_var_params['kwargs']):
            if key not in all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method reports_get_organisation_timesheet_file_attachments" % key
                )
            local_var_params[key] = val
        del local_var_params['kwargs']
        # verify the required parameter 'start_date' is set
        if self.api_client.client_side_validation and ('start_date' not in local_var_params or  # noqa: E501
                                                        local_var_params['start_date'] is None):  # noqa: E501
            raise ApiValueError("Missing the required parameter `start_date` when calling `reports_get_organisation_timesheet_file_attachments`")  # noqa: E501
        # verify the required parameter 'end_date' is set
        if self.api_client.client_side_validation and ('end_date' not in local_var_params or  # noqa: E501
                                                        local_var_params['end_date'] is None):  # noqa: E501
            raise ApiValueError("Missing the required parameter `end_date` when calling `reports_get_organisation_timesheet_file_attachments`")  # noqa: E501
        # verify the required parameter 'x_chronosheets_auth' is set
        if self.api_client.client_side_validation and ('x_chronosheets_auth' not in local_var_params or  # noqa: E501
                                                        local_var_params['x_chronosheets_auth'] is None):  # noqa: E501
            raise ApiValueError("Missing the required parameter `x_chronosheets_auth` when calling `reports_get_organisation_timesheet_file_attachments`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []
        if 'start_date' in local_var_params and local_var_params['start_date'] is not None:  # noqa: E501
            query_params.append(('StartDate', local_var_params['start_date']))  # noqa: E501
        if 'end_date' in local_var_params and local_var_params['end_date'] is not None:  # noqa: E501
            query_params.append(('EndDate', local_var_params['end_date']))  # noqa: E501
        if 'skip' in local_var_params and local_var_params['skip'] is not None:  # noqa: E501
            query_params.append(('Skip', local_var_params['skip']))  # noqa: E501
        if 'take' in local_var_params and local_var_params['take'] is not None:  # noqa: E501
            query_params.append(('Take', local_var_params['take']))  # noqa: E501
        if 'user_ids' in local_var_params and local_var_params['user_ids'] is not None:  # noqa: E501
            query_params.append(('UserIds', local_var_params['user_ids']))  # noqa: E501

        header_params = {}
        if 'x_chronosheets_auth' in local_var_params:
            header_params['x-chronosheets-auth'] = local_var_params['x_chronosheets_auth']  # noqa: E501

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json', 'text/json', 'application/xml', 'text/xml', 'multipart/form-data'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/Reports/GetOrganisationTimesheetFileAttachments', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='ApiResponseForPaginatedListOrgReportTimesheetFileAttachment',  # noqa: E501
            auth_settings=auth_settings,
            async_req=local_var_params.get('async_req'),
            _return_http_data_only=local_var_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=local_var_params.get('_preload_content', True),
            _request_timeout=local_var_params.get('_request_timeout'),
            collection_formats=collection_formats)

    def reports_get_organisation_transcripts(self, start_date, end_date, x_chronosheets_auth, **kwargs):  # noqa: E501
        """Reports on Organisation transcripts (When an audio file is attached, it will be automatically transcribed, these are the transcriptions)    Requires the 'ReportAdmin' permission.  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.reports_get_organisation_transcripts(start_date, end_date, x_chronosheets_auth, async_req=True)
        >>> result = thread.get()

        :param async_req bool: execute request asynchronously
        :param datetime start_date: The start date for the date range.  Report data in the response is after this date (required)
        :param datetime end_date: The end date for the date range.  Report data in the response is before this date (required)
        :param str x_chronosheets_auth: The ChronoSheets Auth Token (required)
        :param int skip: Skip this many items
        :param int take: Take this many items
        :param str user_ids: A comma-separated list of user Ids, if you want to filter the report data to particular users.  If you want all, send a blank string.
        :param str keywords: Search the transcripts by keyword(s)
        :param _preload_content: if False, the urllib3.HTTPResponse object will
                                 be returned without reading/decoding response
                                 data. Default is True.
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :return: ApiResponseForPaginatedListOrgReportTranscript
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        return self.reports_get_organisation_transcripts_with_http_info(start_date, end_date, x_chronosheets_auth, **kwargs)  # noqa: E501

    def reports_get_organisation_transcripts_with_http_info(self, start_date, end_date, x_chronosheets_auth, **kwargs):  # noqa: E501
        """Reports on Organisation transcripts (When an audio file is attached, it will be automatically transcribed, these are the transcriptions)    Requires the 'ReportAdmin' permission.  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.reports_get_organisation_transcripts_with_http_info(start_date, end_date, x_chronosheets_auth, async_req=True)
        >>> result = thread.get()

        :param async_req bool: execute request asynchronously
        :param datetime start_date: The start date for the date range.  Report data in the response is after this date (required)
        :param datetime end_date: The end date for the date range.  Report data in the response is before this date (required)
        :param str x_chronosheets_auth: The ChronoSheets Auth Token (required)
        :param int skip: Skip this many items
        :param int take: Take this many items
        :param str user_ids: A comma-separated list of user Ids, if you want to filter the report data to particular users.  If you want all, send a blank string.
        :param str keywords: Search the transcripts by keyword(s)
        :param _return_http_data_only: response data without head status code
                                       and headers
        :param _preload_content: if False, the urllib3.HTTPResponse object will
                                 be returned without reading/decoding response
                                 data. Default is True.
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :return: tuple(ApiResponseForPaginatedListOrgReportTranscript, status_code(int), headers(HTTPHeaderDict))
                 If the method is called asynchronously,
                 returns the request thread.
        """

        local_var_params = locals()

        all_params = [
            'start_date',
            'end_date',
            'x_chronosheets_auth',
            'skip',
            'take',
            'user_ids',
            'keywords'
        ]
        all_params.extend(
            [
                'async_req',
                '_return_http_data_only',
                '_preload_content',
                '_request_timeout'
            ]
        )

        for key, val in six.iteritems(local_var_params['kwargs']):
            if key not in all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method reports_get_organisation_transcripts" % key
                )
            local_var_params[key] = val
        del local_var_params['kwargs']
        # verify the required parameter 'start_date' is set
        if self.api_client.client_side_validation and ('start_date' not in local_var_params or  # noqa: E501
                                                        local_var_params['start_date'] is None):  # noqa: E501
            raise ApiValueError("Missing the required parameter `start_date` when calling `reports_get_organisation_transcripts`")  # noqa: E501
        # verify the required parameter 'end_date' is set
        if self.api_client.client_side_validation and ('end_date' not in local_var_params or  # noqa: E501
                                                        local_var_params['end_date'] is None):  # noqa: E501
            raise ApiValueError("Missing the required parameter `end_date` when calling `reports_get_organisation_transcripts`")  # noqa: E501
        # verify the required parameter 'x_chronosheets_auth' is set
        if self.api_client.client_side_validation and ('x_chronosheets_auth' not in local_var_params or  # noqa: E501
                                                        local_var_params['x_chronosheets_auth'] is None):  # noqa: E501
            raise ApiValueError("Missing the required parameter `x_chronosheets_auth` when calling `reports_get_organisation_transcripts`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []
        if 'start_date' in local_var_params and local_var_params['start_date'] is not None:  # noqa: E501
            query_params.append(('StartDate', local_var_params['start_date']))  # noqa: E501
        if 'end_date' in local_var_params and local_var_params['end_date'] is not None:  # noqa: E501
            query_params.append(('EndDate', local_var_params['end_date']))  # noqa: E501
        if 'skip' in local_var_params and local_var_params['skip'] is not None:  # noqa: E501
            query_params.append(('Skip', local_var_params['skip']))  # noqa: E501
        if 'take' in local_var_params and local_var_params['take'] is not None:  # noqa: E501
            query_params.append(('Take', local_var_params['take']))  # noqa: E501
        if 'user_ids' in local_var_params and local_var_params['user_ids'] is not None:  # noqa: E501
            query_params.append(('UserIds', local_var_params['user_ids']))  # noqa: E501
        if 'keywords' in local_var_params and local_var_params['keywords'] is not None:  # noqa: E501
            query_params.append(('Keywords', local_var_params['keywords']))  # noqa: E501

        header_params = {}
        if 'x_chronosheets_auth' in local_var_params:
            header_params['x-chronosheets-auth'] = local_var_params['x_chronosheets_auth']  # noqa: E501

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json', 'text/json', 'application/xml', 'text/xml', 'multipart/form-data'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/Reports/GetOrganisationTranscripts', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='ApiResponseForPaginatedListOrgReportTranscript',  # noqa: E501
            auth_settings=auth_settings,
            async_req=local_var_params.get('async_req'),
            _return_http_data_only=local_var_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=local_var_params.get('_preload_content', True),
            _request_timeout=local_var_params.get('_request_timeout'),
            collection_formats=collection_formats)

    def reports_get_organisation_trips(self, start_date, end_date, x_chronosheets_auth, **kwargs):  # noqa: E501
        """Reports on Organisation trips (GPS tracking from whole organisation).    Requires the 'ReportAdmin' permission.  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.reports_get_organisation_trips(start_date, end_date, x_chronosheets_auth, async_req=True)
        >>> result = thread.get()

        :param async_req bool: execute request asynchronously
        :param datetime start_date: The start date for the date range.  Report data in the response is after this date (required)
        :param datetime end_date: The end date for the date range.  Report data in the response is before this date (required)
        :param str x_chronosheets_auth: The ChronoSheets Auth Token (required)
        :param int skip: Skip this many items
        :param int take: Take this many items
        :param str user_ids: A comma-separated list of user Ids, if you want to filter the report data to particular users.  If you want all, send a blank string.
        :param _preload_content: if False, the urllib3.HTTPResponse object will
                                 be returned without reading/decoding response
                                 data. Default is True.
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :return: ApiResponseForPaginatedListOrgReportTrip
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        return self.reports_get_organisation_trips_with_http_info(start_date, end_date, x_chronosheets_auth, **kwargs)  # noqa: E501

    def reports_get_organisation_trips_with_http_info(self, start_date, end_date, x_chronosheets_auth, **kwargs):  # noqa: E501
        """Reports on Organisation trips (GPS tracking from whole organisation).    Requires the 'ReportAdmin' permission.  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.reports_get_organisation_trips_with_http_info(start_date, end_date, x_chronosheets_auth, async_req=True)
        >>> result = thread.get()

        :param async_req bool: execute request asynchronously
        :param datetime start_date: The start date for the date range.  Report data in the response is after this date (required)
        :param datetime end_date: The end date for the date range.  Report data in the response is before this date (required)
        :param str x_chronosheets_auth: The ChronoSheets Auth Token (required)
        :param int skip: Skip this many items
        :param int take: Take this many items
        :param str user_ids: A comma-separated list of user Ids, if you want to filter the report data to particular users.  If you want all, send a blank string.
        :param _return_http_data_only: response data without head status code
                                       and headers
        :param _preload_content: if False, the urllib3.HTTPResponse object will
                                 be returned without reading/decoding response
                                 data. Default is True.
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :return: tuple(ApiResponseForPaginatedListOrgReportTrip, status_code(int), headers(HTTPHeaderDict))
                 If the method is called asynchronously,
                 returns the request thread.
        """

        local_var_params = locals()

        all_params = [
            'start_date',
            'end_date',
            'x_chronosheets_auth',
            'skip',
            'take',
            'user_ids'
        ]
        all_params.extend(
            [
                'async_req',
                '_return_http_data_only',
                '_preload_content',
                '_request_timeout'
            ]
        )

        for key, val in six.iteritems(local_var_params['kwargs']):
            if key not in all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method reports_get_organisation_trips" % key
                )
            local_var_params[key] = val
        del local_var_params['kwargs']
        # verify the required parameter 'start_date' is set
        if self.api_client.client_side_validation and ('start_date' not in local_var_params or  # noqa: E501
                                                        local_var_params['start_date'] is None):  # noqa: E501
            raise ApiValueError("Missing the required parameter `start_date` when calling `reports_get_organisation_trips`")  # noqa: E501
        # verify the required parameter 'end_date' is set
        if self.api_client.client_side_validation and ('end_date' not in local_var_params or  # noqa: E501
                                                        local_var_params['end_date'] is None):  # noqa: E501
            raise ApiValueError("Missing the required parameter `end_date` when calling `reports_get_organisation_trips`")  # noqa: E501
        # verify the required parameter 'x_chronosheets_auth' is set
        if self.api_client.client_side_validation and ('x_chronosheets_auth' not in local_var_params or  # noqa: E501
                                                        local_var_params['x_chronosheets_auth'] is None):  # noqa: E501
            raise ApiValueError("Missing the required parameter `x_chronosheets_auth` when calling `reports_get_organisation_trips`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []
        if 'start_date' in local_var_params and local_var_params['start_date'] is not None:  # noqa: E501
            query_params.append(('StartDate', local_var_params['start_date']))  # noqa: E501
        if 'end_date' in local_var_params and local_var_params['end_date'] is not None:  # noqa: E501
            query_params.append(('EndDate', local_var_params['end_date']))  # noqa: E501
        if 'skip' in local_var_params and local_var_params['skip'] is not None:  # noqa: E501
            query_params.append(('Skip', local_var_params['skip']))  # noqa: E501
        if 'take' in local_var_params and local_var_params['take'] is not None:  # noqa: E501
            query_params.append(('Take', local_var_params['take']))  # noqa: E501
        if 'user_ids' in local_var_params and local_var_params['user_ids'] is not None:  # noqa: E501
            query_params.append(('UserIds', local_var_params['user_ids']))  # noqa: E501

        header_params = {}
        if 'x_chronosheets_auth' in local_var_params:
            header_params['x-chronosheets-auth'] = local_var_params['x_chronosheets_auth']  # noqa: E501

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json', 'text/json', 'application/xml', 'text/xml', 'multipart/form-data'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/Reports/GetOrganisationTrips', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='ApiResponseForPaginatedListOrgReportTrip',  # noqa: E501
            auth_settings=auth_settings,
            async_req=local_var_params.get('async_req'),
            _return_http_data_only=local_var_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=local_var_params.get('_preload_content', True),
            _request_timeout=local_var_params.get('_request_timeout'),
            collection_formats=collection_formats)

    def reports_get_raw_data_admin(self, start_date, end_date, x_chronosheets_auth, **kwargs):  # noqa: E501
        """Get Timesheets Raw Data.  This data details each timesheet record.  These are the organisation wide timesheet records, with data from potentially all employees.    Requires the 'ReportAdmin' permission.  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.reports_get_raw_data_admin(start_date, end_date, x_chronosheets_auth, async_req=True)
        >>> result = thread.get()

        :param async_req bool: execute request asynchronously
        :param datetime start_date: The start date for the date range.  Report data in the response is after this date (required)
        :param datetime end_date: The end date for the date range.  Report data in the response is before this date (required)
        :param str x_chronosheets_auth: The ChronoSheets Auth Token (required)
        :param str user_ids: A comma-separated list of user Ids, if you want to filter the report data to particular users.  If you want all, send a blank string.
        :param str sort: Decide which column to sort on
        :param str order: Decide which direction to sort the column
        :param int skip: Skip this many rows
        :param int take: Take this many rows
        :param _preload_content: if False, the urllib3.HTTPResponse object will
                                 be returned without reading/decoding response
                                 data. Default is True.
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :return: ApiResponseForPaginatedListRawReportItem
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        return self.reports_get_raw_data_admin_with_http_info(start_date, end_date, x_chronosheets_auth, **kwargs)  # noqa: E501

    def reports_get_raw_data_admin_with_http_info(self, start_date, end_date, x_chronosheets_auth, **kwargs):  # noqa: E501
        """Get Timesheets Raw Data.  This data details each timesheet record.  These are the organisation wide timesheet records, with data from potentially all employees.    Requires the 'ReportAdmin' permission.  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.reports_get_raw_data_admin_with_http_info(start_date, end_date, x_chronosheets_auth, async_req=True)
        >>> result = thread.get()

        :param async_req bool: execute request asynchronously
        :param datetime start_date: The start date for the date range.  Report data in the response is after this date (required)
        :param datetime end_date: The end date for the date range.  Report data in the response is before this date (required)
        :param str x_chronosheets_auth: The ChronoSheets Auth Token (required)
        :param str user_ids: A comma-separated list of user Ids, if you want to filter the report data to particular users.  If you want all, send a blank string.
        :param str sort: Decide which column to sort on
        :param str order: Decide which direction to sort the column
        :param int skip: Skip this many rows
        :param int take: Take this many rows
        :param _return_http_data_only: response data without head status code
                                       and headers
        :param _preload_content: if False, the urllib3.HTTPResponse object will
                                 be returned without reading/decoding response
                                 data. Default is True.
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :return: tuple(ApiResponseForPaginatedListRawReportItem, status_code(int), headers(HTTPHeaderDict))
                 If the method is called asynchronously,
                 returns the request thread.
        """

        local_var_params = locals()

        all_params = [
            'start_date',
            'end_date',
            'x_chronosheets_auth',
            'user_ids',
            'sort',
            'order',
            'skip',
            'take'
        ]
        all_params.extend(
            [
                'async_req',
                '_return_http_data_only',
                '_preload_content',
                '_request_timeout'
            ]
        )

        for key, val in six.iteritems(local_var_params['kwargs']):
            if key not in all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method reports_get_raw_data_admin" % key
                )
            local_var_params[key] = val
        del local_var_params['kwargs']
        # verify the required parameter 'start_date' is set
        if self.api_client.client_side_validation and ('start_date' not in local_var_params or  # noqa: E501
                                                        local_var_params['start_date'] is None):  # noqa: E501
            raise ApiValueError("Missing the required parameter `start_date` when calling `reports_get_raw_data_admin`")  # noqa: E501
        # verify the required parameter 'end_date' is set
        if self.api_client.client_side_validation and ('end_date' not in local_var_params or  # noqa: E501
                                                        local_var_params['end_date'] is None):  # noqa: E501
            raise ApiValueError("Missing the required parameter `end_date` when calling `reports_get_raw_data_admin`")  # noqa: E501
        # verify the required parameter 'x_chronosheets_auth' is set
        if self.api_client.client_side_validation and ('x_chronosheets_auth' not in local_var_params or  # noqa: E501
                                                        local_var_params['x_chronosheets_auth'] is None):  # noqa: E501
            raise ApiValueError("Missing the required parameter `x_chronosheets_auth` when calling `reports_get_raw_data_admin`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []
        if 'start_date' in local_var_params and local_var_params['start_date'] is not None:  # noqa: E501
            query_params.append(('StartDate', local_var_params['start_date']))  # noqa: E501
        if 'end_date' in local_var_params and local_var_params['end_date'] is not None:  # noqa: E501
            query_params.append(('EndDate', local_var_params['end_date']))  # noqa: E501
        if 'user_ids' in local_var_params and local_var_params['user_ids'] is not None:  # noqa: E501
            query_params.append(('UserIds', local_var_params['user_ids']))  # noqa: E501
        if 'sort' in local_var_params and local_var_params['sort'] is not None:  # noqa: E501
            query_params.append(('Sort', local_var_params['sort']))  # noqa: E501
        if 'order' in local_var_params and local_var_params['order'] is not None:  # noqa: E501
            query_params.append(('Order', local_var_params['order']))  # noqa: E501
        if 'skip' in local_var_params and local_var_params['skip'] is not None:  # noqa: E501
            query_params.append(('Skip', local_var_params['skip']))  # noqa: E501
        if 'take' in local_var_params and local_var_params['take'] is not None:  # noqa: E501
            query_params.append(('Take', local_var_params['take']))  # noqa: E501

        header_params = {}
        if 'x_chronosheets_auth' in local_var_params:
            header_params['x-chronosheets-auth'] = local_var_params['x_chronosheets_auth']  # noqa: E501

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json', 'text/json', 'application/xml', 'text/xml', 'multipart/form-data'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/Reports/GetRawDataAdmin', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='ApiResponseForPaginatedListRawReportItem',  # noqa: E501
            auth_settings=auth_settings,
            async_req=local_var_params.get('async_req'),
            _return_http_data_only=local_var_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=local_var_params.get('_preload_content', True),
            _request_timeout=local_var_params.get('_request_timeout'),
            collection_formats=collection_formats)

    def reports_project_costings_admin(self, start_date, end_date, x_chronosheets_auth, **kwargs):  # noqa: E501
        """Gets project cost estimations VS actual cost for date range and users.    Requires the 'ReportAdmin' permission.  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.reports_project_costings_admin(start_date, end_date, x_chronosheets_auth, async_req=True)
        >>> result = thread.get()

        :param async_req bool: execute request asynchronously
        :param datetime start_date: The start date for the date range.  Report data in the response is after this date (required)
        :param datetime end_date: The end date for the date range.  Report data in the response is before this date (required)
        :param str x_chronosheets_auth: The ChronoSheets Auth Token (required)
        :param str user_ids: A comma-separated list of user Ids, if you want to filter the report data to particular users.  If you want all, send a blank string.
        :param _preload_content: if False, the urllib3.HTTPResponse object will
                                 be returned without reading/decoding response
                                 data. Default is True.
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :return: ApiResponseListProjectCostingReportItem
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        return self.reports_project_costings_admin_with_http_info(start_date, end_date, x_chronosheets_auth, **kwargs)  # noqa: E501

    def reports_project_costings_admin_with_http_info(self, start_date, end_date, x_chronosheets_auth, **kwargs):  # noqa: E501
        """Gets project cost estimations VS actual cost for date range and users.    Requires the 'ReportAdmin' permission.  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.reports_project_costings_admin_with_http_info(start_date, end_date, x_chronosheets_auth, async_req=True)
        >>> result = thread.get()

        :param async_req bool: execute request asynchronously
        :param datetime start_date: The start date for the date range.  Report data in the response is after this date (required)
        :param datetime end_date: The end date for the date range.  Report data in the response is before this date (required)
        :param str x_chronosheets_auth: The ChronoSheets Auth Token (required)
        :param str user_ids: A comma-separated list of user Ids, if you want to filter the report data to particular users.  If you want all, send a blank string.
        :param _return_http_data_only: response data without head status code
                                       and headers
        :param _preload_content: if False, the urllib3.HTTPResponse object will
                                 be returned without reading/decoding response
                                 data. Default is True.
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :return: tuple(ApiResponseListProjectCostingReportItem, status_code(int), headers(HTTPHeaderDict))
                 If the method is called asynchronously,
                 returns the request thread.
        """

        local_var_params = locals()

        all_params = [
            'start_date',
            'end_date',
            'x_chronosheets_auth',
            'user_ids'
        ]
        all_params.extend(
            [
                'async_req',
                '_return_http_data_only',
                '_preload_content',
                '_request_timeout'
            ]
        )

        for key, val in six.iteritems(local_var_params['kwargs']):
            if key not in all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method reports_project_costings_admin" % key
                )
            local_var_params[key] = val
        del local_var_params['kwargs']
        # verify the required parameter 'start_date' is set
        if self.api_client.client_side_validation and ('start_date' not in local_var_params or  # noqa: E501
                                                        local_var_params['start_date'] is None):  # noqa: E501
            raise ApiValueError("Missing the required parameter `start_date` when calling `reports_project_costings_admin`")  # noqa: E501
        # verify the required parameter 'end_date' is set
        if self.api_client.client_side_validation and ('end_date' not in local_var_params or  # noqa: E501
                                                        local_var_params['end_date'] is None):  # noqa: E501
            raise ApiValueError("Missing the required parameter `end_date` when calling `reports_project_costings_admin`")  # noqa: E501
        # verify the required parameter 'x_chronosheets_auth' is set
        if self.api_client.client_side_validation and ('x_chronosheets_auth' not in local_var_params or  # noqa: E501
                                                        local_var_params['x_chronosheets_auth'] is None):  # noqa: E501
            raise ApiValueError("Missing the required parameter `x_chronosheets_auth` when calling `reports_project_costings_admin`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []
        if 'start_date' in local_var_params and local_var_params['start_date'] is not None:  # noqa: E501
            query_params.append(('StartDate', local_var_params['start_date']))  # noqa: E501
        if 'end_date' in local_var_params and local_var_params['end_date'] is not None:  # noqa: E501
            query_params.append(('EndDate', local_var_params['end_date']))  # noqa: E501
        if 'user_ids' in local_var_params and local_var_params['user_ids'] is not None:  # noqa: E501
            query_params.append(('UserIds', local_var_params['user_ids']))  # noqa: E501

        header_params = {}
        if 'x_chronosheets_auth' in local_var_params:
            header_params['x-chronosheets-auth'] = local_var_params['x_chronosheets_auth']  # noqa: E501

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json', 'text/json', 'application/xml', 'text/xml', 'multipart/form-data'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/Reports/ProjectCostingsAdmin', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='ApiResponseListProjectCostingReportItem',  # noqa: E501
            auth_settings=auth_settings,
            async_req=local_var_params.get('async_req'),
            _return_http_data_only=local_var_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=local_var_params.get('_preload_content', True),
            _request_timeout=local_var_params.get('_request_timeout'),
            collection_formats=collection_formats)

    def reports_user_jobs_over_time(self, start_date, end_date, x_chronosheets_auth, **kwargs):  # noqa: E501
        """Timeseries jobs data for the logged in user.    Requires the 'ViewOwnReports' or 'SubmitTimesheets'.  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.reports_user_jobs_over_time(start_date, end_date, x_chronosheets_auth, async_req=True)
        >>> result = thread.get()

        :param async_req bool: execute request asynchronously
        :param datetime start_date: The start date for the date range.  Report data in the response is after this date (required)
        :param datetime end_date: The end date for the date range.  Report data in the response is before this date (required)
        :param str x_chronosheets_auth: The ChronoSheets Auth Token (required)
        :param _preload_content: if False, the urllib3.HTTPResponse object will
                                 be returned without reading/decoding response
                                 data. Default is True.
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :return: ApiResponseListJobSeriesReportItem
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        return self.reports_user_jobs_over_time_with_http_info(start_date, end_date, x_chronosheets_auth, **kwargs)  # noqa: E501

    def reports_user_jobs_over_time_with_http_info(self, start_date, end_date, x_chronosheets_auth, **kwargs):  # noqa: E501
        """Timeseries jobs data for the logged in user.    Requires the 'ViewOwnReports' or 'SubmitTimesheets'.  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.reports_user_jobs_over_time_with_http_info(start_date, end_date, x_chronosheets_auth, async_req=True)
        >>> result = thread.get()

        :param async_req bool: execute request asynchronously
        :param datetime start_date: The start date for the date range.  Report data in the response is after this date (required)
        :param datetime end_date: The end date for the date range.  Report data in the response is before this date (required)
        :param str x_chronosheets_auth: The ChronoSheets Auth Token (required)
        :param _return_http_data_only: response data without head status code
                                       and headers
        :param _preload_content: if False, the urllib3.HTTPResponse object will
                                 be returned without reading/decoding response
                                 data. Default is True.
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :return: tuple(ApiResponseListJobSeriesReportItem, status_code(int), headers(HTTPHeaderDict))
                 If the method is called asynchronously,
                 returns the request thread.
        """

        local_var_params = locals()

        all_params = [
            'start_date',
            'end_date',
            'x_chronosheets_auth'
        ]
        all_params.extend(
            [
                'async_req',
                '_return_http_data_only',
                '_preload_content',
                '_request_timeout'
            ]
        )

        for key, val in six.iteritems(local_var_params['kwargs']):
            if key not in all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method reports_user_jobs_over_time" % key
                )
            local_var_params[key] = val
        del local_var_params['kwargs']
        # verify the required parameter 'start_date' is set
        if self.api_client.client_side_validation and ('start_date' not in local_var_params or  # noqa: E501
                                                        local_var_params['start_date'] is None):  # noqa: E501
            raise ApiValueError("Missing the required parameter `start_date` when calling `reports_user_jobs_over_time`")  # noqa: E501
        # verify the required parameter 'end_date' is set
        if self.api_client.client_side_validation and ('end_date' not in local_var_params or  # noqa: E501
                                                        local_var_params['end_date'] is None):  # noqa: E501
            raise ApiValueError("Missing the required parameter `end_date` when calling `reports_user_jobs_over_time`")  # noqa: E501
        # verify the required parameter 'x_chronosheets_auth' is set
        if self.api_client.client_side_validation and ('x_chronosheets_auth' not in local_var_params or  # noqa: E501
                                                        local_var_params['x_chronosheets_auth'] is None):  # noqa: E501
            raise ApiValueError("Missing the required parameter `x_chronosheets_auth` when calling `reports_user_jobs_over_time`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []
        if 'start_date' in local_var_params and local_var_params['start_date'] is not None:  # noqa: E501
            query_params.append(('StartDate', local_var_params['start_date']))  # noqa: E501
        if 'end_date' in local_var_params and local_var_params['end_date'] is not None:  # noqa: E501
            query_params.append(('EndDate', local_var_params['end_date']))  # noqa: E501

        header_params = {}
        if 'x_chronosheets_auth' in local_var_params:
            header_params['x-chronosheets-auth'] = local_var_params['x_chronosheets_auth']  # noqa: E501

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json', 'text/json', 'application/xml', 'text/xml', 'multipart/form-data'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/Reports/UserJobsOverTime', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='ApiResponseListJobSeriesReportItem',  # noqa: E501
            auth_settings=auth_settings,
            async_req=local_var_params.get('async_req'),
            _return_http_data_only=local_var_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=local_var_params.get('_preload_content', True),
            _request_timeout=local_var_params.get('_request_timeout'),
            collection_formats=collection_formats)
